import { Inter } from "next/font/google";
import "./globals.css";
import NavRender from "@/components/navbar/nav-render";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter} antialiased bg-zinc-100 min-h-screen flex flex-col`}
        >
          <Provider children={children} />
        </body>
      </html>
    </ClerkProvider>
  );
}
